from django.urls import path

from .views import (
    get_banners,
    get_offers,
    register,
    verify_otp,
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    get_posts,
    create_post,
    create_comment,
    get_comments,
    admin_register,
    get_classes,
    get_tutor_profile,
    service_post,
    AttendanceViewSet,
    UserProfileDetailsView,
    create_or_update_user_additional_info,
    get_testimonials,
    callback_request,
    create_staff_user,
    easebuzz_webhook,
    create_subscription,
    verify_and_subscribe,
    subscription_form,
    get_user_subscription,
    forgot_password,
    reset_password,
    get_all_videos,
    get_all_faqs,
    create_rating,

)

urlpatterns = [
    path('banners/', get_banners, name='get_banners'),
    path('offers/', get_offers, name='get_offers'),
    path('register/', register, name='register_user'),
    path('verify-otp/', verify_otp, name='verify_otp'),
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('posts/', get_posts, name='get_posts'),
    path('posts/create/', create_post, name='create_post'),
    path('posts/<int:post_id>/comments/', get_comments, name='get_comments'),
    path('posts/<int:post_id>/comments/create/', create_comment, name='create_comment'),
    path('admin/register/', admin_register, name='admin-register'),
    path('classes/', get_classes, name='get_classes'),
    path('get_tutor_profile/', get_tutor_profile, name='get_tutor_profile'),
    path('service-post/', service_post, name='service_post'),
    path('attendance/mark_attendance/', AttendanceViewSet.as_view({'post': 'mark_attendance'}), name='mark_attendance'),
    path('attendance/monthly_attendance/<int:user_id>/', AttendanceViewSet.as_view({'get': 'monthly_attendance'}),
         name='monthly_attendance'),
    path('profile/details/', UserProfileDetailsView.as_view(), name='profile_details'),
    path('user-profile/<int:user_id>/additional-info/', create_or_update_user_additional_info, name='user-profile-additional-info'),
    path('testimonials/', get_testimonials, name='get_testimonials'),
    path('callback/', callback_request, name='create-callback-request'),
    path("create-staff/", create_staff_user, name="create_staff_user"),
    path('webhook/', easebuzz_webhook, name='easebuzz_webhook'),
    path('create-subscription/', create_subscription, name='create-subscription'),
    path('verify-subscribe/', verify_and_subscribe, name='verify-subscribe'),
    path("create-subscriptions-manually/", subscription_form, name="subscription_form"),
    path("fetch-subscription/", get_user_subscription, name="get_user_subscription"),
    path("forgot-password/", forgot_password, name="forgot_password"),
    path("reset_password/", reset_password, name="reset_password"),
    path('videoUrl/', get_all_videos, name='get-all-videos'),  # List and Create
    path('faq/', get_all_faqs, name='get-all-faqs'),
    path('ratings/create/', create_rating, name='create_rating'),  # Create rating

]
